"""empty message

Revision ID: 4e8a2e08aa84
Revises:
Create Date: 2024-02-19 02:04:31.272743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e8a2e08aa84'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'table_user',
        sa.Column('id', sa.Integer(), nullable=False, comment='id пользователя'),
        sa.Column('uid', sa.UUID(), nullable=False, comment='uuid пользователя'),
        sa.Column('first_name', sa.String(), nullable=False, comment='имя пользователя'),
        sa.Column('second_name', sa.String(), nullable=False, comment='фамилия пользователя'),
        sa.Column('email', sa.String(), nullable=False, comment='email пользователя'),
        sa.Column('hashed_password', sa.String(), nullable=False, comment='хеш пароля пользователя'),
        sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='дата регистрации пользователя'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_user_email'), 'table_user', ['email'], unique=True)
    op.create_index(op.f('ix_table_user_id'), 'table_user', ['id'], unique=False)
    op.create_index(op.f('ix_table_user_registered_at'), 'table_user', ['registered_at'], unique=False)
    op.create_index(op.f('ix_table_user_uid'), 'table_user', ['uid'], unique=True)
    op.create_table(
        'table_device',
        sa.Column('id', sa.Integer(), nullable=False, comment='id устройства'),
        sa.Column('serial', sa.String(), nullable=False, comment='Серийный номер устройства'),
        sa.Column('user_id', sa.Integer(), nullable=False, comment='Пользователь устройства'),
        sa.ForeignKeyConstraint(['user_id'], ['table_user.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('serial')
    )
    op.create_index(op.f('ix_table_device_id'), 'table_device', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_device_id'), table_name='table_device')
    op.drop_table('table_device')
    op.drop_index(op.f('ix_table_user_uid'), table_name='table_user')
    op.drop_index(op.f('ix_table_user_registered_at'), table_name='table_user')
    op.drop_index(op.f('ix_table_user_id'), table_name='table_user')
    op.drop_index(op.f('ix_table_user_email'), table_name='table_user')
    op.drop_table('table_user')
    # ### end Alembic commands ###
