"""empty message

Revision ID: d774b7722231
Revises: 0659d8bc2d60
Create Date: 2024-02-19 03:14:07.889355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd774b7722231'
down_revision: Union[str, None] = '0659d8bc2d60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_device_data', sa.Column('registered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='дата регистрации пользователя'))
    op.create_index(op.f('ix_table_device_data_registered_at'), 'table_device_data', ['registered_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_device_data_registered_at'), table_name='table_device_data')
    op.drop_column('table_device_data', 'registered_at')
    # ### end Alembic commands ###
