"""empty message

Revision ID: 0659d8bc2d60
Revises: 4e8a2e08aa84
Create Date: 2024-02-19 02:58:34.927449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0659d8bc2d60'
down_revision: Union[str, None] = '4e8a2e08aa84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'table_device_data',
        sa.Column('id', sa.Integer(), nullable=False, comment='id записи'),
        sa.Column('data_x', sa.Float(), nullable=False, comment='Данные "x"'),
        sa.Column('data_y', sa.Float(), nullable=False, comment='Данные "y"'),
        sa.Column('data_z', sa.Float(), nullable=False, comment='Данные "z"'),
        sa.Column('device_id', sa.Integer(), nullable=False, comment='Устройство'),
        sa.ForeignKeyConstraint(['device_id'], ['table_device.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_device_data_id'), 'table_device_data', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_table_device_data_id'), table_name='table_device_data')
    op.drop_table('table_device_data')
    # ### end Alembic commands ###
